/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/AppLayout/AppLayout.vue')['default']
    CommandResult: typeof import('./components/CommandResult.vue')['default']
    ConnectionDialog: typeof import('./components/ConnectionDialog.vue')['default']
    ConnectionTree: typeof import('./components/ConnectionTree/ConnectionTree.vue')['default']
    ContextMenu: typeof import('./components/ConnectionTree/ContextMenu.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    FunctionPanel: typeof import('./components/FunctionPanel/FunctionPanel.vue')['default']
    HeaderBar: typeof import('./components/HeaderBar/HeaderBar.vue')['default']
    MainPanel: typeof import('./components/MainPanel/index.vue')['default']
    ObjectFunctionPanel: typeof import('./components/ObjectPanel/components/ObjectFunctionPanel.vue')['default']
    ObjectPanel: typeof import('./components/ObjectPanel/ObjectPanel.vue')['default']
    ObjectTablePanel: typeof import('./components/ObjectPanel/components/ObjectTablePanel.vue')['default']
    ObjectViewPanel: typeof import('./components/ObjectPanel/components/ObjectViewPanel.vue')['default']
    PropertiesPanel: typeof import('./components/PropertiesPanel/PropertiesPanel.vue')['default']
    QueryEditor: typeof import('./components/QueryEditor.vue')['default']
    TerminalConsole: typeof import('./components/TerminalConsole.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
